name: Deploy cdn

on:
    push:
        branches: [master]
        paths-ignore:
            - "README.md"
            - "LICENSE"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd ~/deploy/${{ github.event.repository.name }}
                      git reset --hard
                      git pull
                      yarn
                      cp ../.env .env
                      yarn deploy
                      pm2 restart ${{ github.event.repository.name }}
